FROM node:12-alpine as builder

WORKDIR /app/

ENV NODE_ENV=dev

COPY package.json ./
COPY tsconfig.json ./
COPY yarn.lock ./
COPY codegen.yml ./
COPY .npmrc ./
COPY ./src ./src
COPY ./public ./public
COPY ./templates ./templates
RUN yarn

LABEL org.opencontainers.image.url="https://dev.azure.com/endeavor-digital/Technology%20Infrastructure/_git/speakers?path=%2FREADME.md"
LABEL org.opencontainers.image.source="https://dev.azure.com/endeavor-digital/Technology%20Infrastructure/_git/speakers"
LABEL org.opencontainers.image.vendor="Endeavor"
LABEL org.opencontainers.image.title="Endeavor Experiences Speakers Frontend"

ENV REACT_APP_ACCOUNTS_URL=https://speakers.endvr/api/accounts
ENV REACT_APP_SPEAKERS_BOOKING_URL=https://speakers.endvr/api/speakers-booking
ENV REACT_APP_SPEAKERS_TALENT_URL=https://speakers.endvr/api/speakers-talent
ENV REACT_APP_IMAGE_PROXY_URL=https://speakers.endvr/

EXPOSE 3000/tcp

ENTRYPOINT ["yarn", "start"]