export const hardCodedTalent = [
  {
    name: "Featured",
    talent: [
      "kevin-hart",
      "alex-rodriguez",
      "glennon-doyle",
      "matthew-mcconaughey",
      "bozoma-saint-john",
      "serena-williams",
    ],
  },
  {
    name: "Diversity, Inclusion & Equity",
    url: "/subtopic/fcf918b9-5bea-449a-84a7-c6f6ec0bf258",
    talent: [
      "tyler-perry",
      "bozoma-saint-john",
      "serena-williams",
      "tarana-burke",
      "austin-channing-brown",
      "w-kamau-bell",
      "hasan-minhaj",
      "lisa-ling",
    ],
  },
  {
    name: "LGBTQIA",
    url: "/type/dc58411e-0b37-49f3-b719-f45f3573b9d8",
    talent: [
      "katie-sowers",
      "lilly-singh",
      "tan-france",
      "adam-rippon",
      "amber-heard",
      "sean-hayes",
      "kate-mc-kinnon",
      "christian-siriano",
    ],
  },
  {
    name: "Leadership",
    url: "/subtopic/651ac688-fcb3-4613-b9cd-674761be6d67",
    talent: [
      "simon-sinek",
      "marcus-lemonis",
      "cecile-richards",
      "billie-jean-king",
      "bill-frist",
      "lori-greiner",
      "michael-strahan",
      "indra-nooyi",
    ],
  },
  {
    name: "Inspiration & Motivation",
    url: "/subtopic/0b020775-73c5-4de8-8a96-f265ebd43feb",
    talent: [
      "kevin-hart",
      "ashley-judd",
      "alex-rodriguez",
      "sully-sullenberger",
      "matthew-mc-conaughey",
      "shaquille-o-neal",
      "maria-sharapova",
      "richard-phillips",
    ],
  },
  {
    name: "Politics",
    url: "/subtopic/d2d901fe-b531-4db8-85b5-0c2920f98cff",
    talent: [
      "rham-emanuel",
      "chris-christie",
      "stacey-abrams",
      "joy-ann-reid",
      "charles-blow",
      "julian-castro",
      "julia-gillard",
      "mika-and-joe-scarborough",
    ],
  },
];
