export const hardCodedTalent = [
  {
    name: "Featured",
    talent: [
      "kevin-hart",
      "alex-rodriguez",
      "glennon-doyle",
      "matthew-mcconaughey",
      "bozoma-saint-john",
      "serena-williams",
    ],
  },
  {
    name: "Diversity, Inclusion & Equity",
    url: "/subtopic/diversity-inclusion",
    talent: [
      "tyler-perry",
      "bozoma-saint-john",
      "serena-williams",
      "tarana-burke",
      "austin-channing-brown",
      "w-kamau-bell",
      "hasan-minhaj",
      "lisa-ling",
    ],
  },
  {
    name: "LGBTQIA",
    url: "/type/lgbtqia",
    talent: [
      "katie-sowers",
      "lilly-singh",
      "tan-france",
      "adam-rippon",
      "amber-heard",
      "sean-hayes",
      "kate-mc-kinnon",
      "christian-siriano",
    ],
  },
  {
    name: "Leadership",
    url: "/subtopic/leadership-strategic-management",
    talent: [
      "simon-sinek",
      "marcus-lemonis",
      "cecile-richards",
      "billie-jean-king",
      "bill-frist",
      "lori-greiner",
      "michael-strahan",
      "indra-nooyi",
    ],
  },
  {
    name: "Inspiration & Motivation",
    url: "/subtopic/personal-growth-inspiration",
    talent: [
      "kevin-hart",
      "ashley-judd",
      "alex-rodriguez",
      "sully-sullenberger",
      "matthew-mc-conaughey",
      "shaquille-o-neal",
      "maria-sharapova",
      "richard-phillips",
    ],
  },
  {
    name: "Politics",
    url: "/subtopic/u-s-politics-government",
    talent: [
      "rham-emanuel",
      "chris-christie",
      "stacey-abrams",
      "joy-ann-reid",
      "charles-blow",
      "julian-castro",
      "julia-gillard",
      "mika-and-joe-scarborough",
    ],
  },
];
